version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: tg_bot
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # environment:
    #   - REDIS_PASSWORD: 
    command: redis-server --appendonly yes --requirepass qwerty123

volumes:
  db_data:
  redis_data: